### ISSUE TITLE
Heap explore TODO list as well as TOC

### ISSUE THREAD

**Issue by iromise** [ctf-wiki/ctf-wiki#42]
下面的内容既可以看做是堆利用中的 TODO list，也可以视为堆利用(以glibc为例介绍)中所希望形成的目录。目前感觉对于所需要写的基本内容有以下这么多，但是如何组织的合理，还有待考虑。

- [x] 基本堆介绍 
- [x] 堆相关数据结构
- [x] 深入理解堆分配与回收
- [x] 基本堆利用方式
   - [x] Heap OverFlow
   - [x] off by one
   - [x] chunk extend
   - [x] Use After Free
   - [x] Unlink
- [x] FastBin Attack
  - [x] FastBin Double Free
  - [x] House of Sprit
  - [x] Arbitrary Alloc
- [x] House of Force
- [x] unsorted bin attack ( **zerostorage to be done on the lastest Ubuntu 16.04** )
- [x] House of Lore  (**require example**)
- [ ] Heap Spray
- [ ] Heap fengshui
- [x] House of Einherjar
- [ ] House of Rabbit
- [x] House of Orange
- [ ] Many others

如果有任何可以使得这个目录更加合理的建议，欢迎提出。其中合理大概就是
- 有逻辑
- 由浅入深
- 适合新手一步步进阶

**Comment by cclauss** [comment]
Add Python 3 compatibility?

**Comment by iromise** [comment]
This could be a new issue. And for now, we may pay attention to the contents since there is still a lot to be done. And personally, I think this may be a little difficult since there is still a lot package dependency whose version is Python 2.7. And later, we will add the version info in code as long as we can.
